### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Dorky106** [Artentus/ModMyFactory2#14] opened 2020-09-27 19:43 UTC
2) When a modpack is checked off for use, it also checks off mods as semi-use(Square), however if modpacks is checked off, the mods checkbox doesn't change
3) Clicking the modpack checkbox twice, unchecks all the mods but not the modpack
4) Checking the mods checkbox shouldnt affect the modpacks selection at all.  As you want to use all the mods, and it feels off that it's saying you're going to use a modpack.
5) Deleting a mod pack closes the mod manager.

if I get bored I could keep adding to the list.

**Comment by Artentus** [comment] 2020-10-14 01:41
Thank you for reporting all of these.

2. Confirmed, will take a look
3. I can't reproduce this myself, more info would be appreciated
4. Is intentional
5. Should be fixed with 4.0.2

**Closed** 2022-04-11 17:23 UTC
Labels: bug
