### ISSUE TITLE
Crash mod-list.json in use

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory2#9] opened 2020-08-20 12:06 UTC
020-08-20 22:04:21.783 +10:00 [ERR] Application crashed
System.IO.IOException: The process cannot access the file 'E:\JASON\JASON\ModMyFactory2\mods\0.18\mod-list.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at ModMyFactory.Mods.ModFamilyStateGrouping.<SaveToFileAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.ViewModels.ModFamilyViewModel.<OnModsEnabledChanged>d__39.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\ViewModels\ModFamilyViewModel.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ModMyFactoryGUI.Program.<StartAppAsync>d__41.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 334
2020-08-20 22:04:21.793 +10:00 [INF] Saving settings...

**Comment by szentigrad3** [comment] 2020-08-20 16:46
2020-08-21 02:45:18.378 +10:00 [ERR] Application crashed
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> ModMyFactory.WebApi.ResourceNotFoundException: Remote resource not found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.WebApi.WebHelper.<RequestDocumentAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.WebApi.WebHelper.<RequestDocumentAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactory.WebApi.Mods.ModApi.<RequestModInfoAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at ModMyFactory.WebApi.Mods.ModApi.<RequestModInfoAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.Caching.Cache`2.<QueryAsync>d__4.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Caching\Cache.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.ViewModels.ManagerViewModel.<UpdateModsAsync>d__46.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\ViewModels\ManagerViewModel.cs:line 315
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in d:\a\1\s\src\ReactiveUI\RxApp.cs:line 104
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler s, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex) in d:\a\1\s\src\ReactiveUI\RxApp.cs:line 98
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 577
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ModMyFactoryGUI.Program.<StartAppAsync>d__41.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 334
2020-08-21 02:45:18.419 +10:00 [INF] Saving settings...

**Comment by szentigrad3** [comment] 2020-08-24 04:58
error while trying to input login 
2020-08-24 14:57:46.077 +10:00 [ERR] An unknown server error occurred
ModMyFactory.WebApi.ApiException: General API exception
   at ModMyFactory.WebApi.Authentication.<LogInAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.CredentialsManager.<TryLogInAsync>d__10.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\CredentialsManager.cs:line 106
2020-08-24 14:57:46.081 +10:00 [ERR] An unknown server error occurred

**Comment by Artentus** [comment] 2020-09-01 05:59
Your first error is usually not cause by MMF directly but by MMF and some other application getting in each others way, for example Factorio.

The second error is caused by the mod update feature, which is actually not functional yet so I'm not suprised. Mod updating will work in the next major release.

The last error has been resolved in version 2.1.4.

**Comment by szentigrad3** [comment] 2020-09-01 11:14
i don't know how it can be factorio since its not open < the 1st error

**Comment by szentigrad3** [comment] 2020-09-01 11:21
[modpacks.txt](https://github.com/Artentus/ModMyFactory2/files/5155832/modpacks.txt)

after i close the program it stays open in the processes and can't open it again until i killed the proccess and have to delete the modpacks.json ( attached above )

**Comment by Artentus** [comment] 2020-09-02 04:45
Please check if this is still the case for you with 2.2.0

**Comment by szentigrad3** [comment] 2020-09-02 04:52
> Please check if this is still the case for you with 2.2.0

issue still exists

**Comment by Artentus** [comment] 2020-09-14 01:15
Try version 2.2.2 please

**Comment by szentigrad3** [comment] 2020-09-14 02:00
when trying to de-select all mods it just closes straight away now

2020-09-14 11:57:53.151 +10:00 [INF] GUI version: 2.2.2.13-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory v1.1.1.58-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory.BaseTypes v1.1.1.16-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory.Export v1.1.0.20-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory.Localization v1.0.0.6-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory.ModSettings v1.0.0.17-alpha
2020-09-14 11:57:53.173 +10:00 [INF] Using ModMyFactory.WebApi v1.0.2.26-alpha
2020-09-14 11:57:53.174 +10:00 [INF] Using ModMyFactory.Win32 v1.0.0.10-alpha
2020-09-14 11:57:54.477 +10:00 [INF] Language files successfully loaded. Available languages: German, English
2020-09-14 11:57:54.477 +10:00 [INF] Language set to English
2020-09-14 11:57:54.895 +10:00 [INF] Themes successfully loaded; available themes: BaseDark, BaseLight
2020-09-14 11:57:54.899 +10:00 [INF] Theme set to BaseDark
2020-09-14 11:57:58.222 +10:00 [ERR] Application crashed
System.IO.IOException: The process cannot access the file 'E:\JASON\JASON\ModMyFactory2\mods\0.18\mod-list.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at ModMyFactory.Mods.ModFamilyStateGrouping.<SaveToFileAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.ViewModels.ModFamilyViewModel.<OnModsEnabledChanged>d__39.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\ViewModels\ModFamilyViewModel.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ModMyFactoryGUI.Program.<StartAppAsync>d__46.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 348
2020-09-14 11:57:58.230 +10:00 [INF] Saving settings...
2020-09-14 11:57:58.251 +10:00 [INF] Shutting down

**Comment by Artentus** [comment] 2020-09-15 19:09
May have fixed it this time in 2.2.3

**Comment by szentigrad3** [comment] 2020-09-16 00:39
what a pain to fix

2020-09-16 10:37:29.389 +10:00 [INF] GUI version: 2.2.3.14-alpha
2020-09-16 10:37:29.412 +10:00 [INF] Using ModMyFactory v1.2.0.59-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.BaseTypes v1.1.1.16-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.Export v1.2.0.21-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.Localization v1.0.0.6-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.ModSettings v1.0.0.17-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.WebApi v1.0.2.26-alpha
2020-09-16 10:37:29.413 +10:00 [INF] Using ModMyFactory.Win32 v1.0.0.10-alpha
2020-09-16 10:37:41.900 +10:00 [INF] Language files successfully loaded. Available languages: German, English
2020-09-16 10:37:41.900 +10:00 [INF] Language set to English
2020-09-16 10:37:42.893 +10:00 [INF] Themes successfully loaded; available themes: BaseDark, BaseLight
2020-09-16 10:37:42.896 +10:00 [INF] Theme set to BaseDark
2020-09-16 10:37:53.704 +10:00 [ERR] Application crashed
System.IO.IOException: The process cannot access the file 'E:\JASON\JASON\ModMyFactory2\mods\0.18\mod-list.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at ModMyFactory.Mods.ModFamilyStateGrouping.<SaveToFileAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ModMyFactoryGUI.ViewModels.ModFamilyViewModel.<OnModsEnabledChanged>d__39.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\ViewModels\ModFamilyViewModel.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at ModMyFactoryGUI.Program.<StartAppAsync>d__46.MoveNext() in C:\projects\modmyfactory-gui\ModMyFactoryGUI\Program.cs:line 348
2020-09-16 10:37:53.745 +10:00 [INF] Saving settings...
2020-09-16 10:37:53.762 +10:00 [INF] Shutting down

**Comment by Artentus** [comment] 2020-09-16 06:16
It's such a pain because I'm completely unable to reproduce this.

**Comment by szentigrad3** [comment] 2020-09-16 08:01
anything i can do on my end to help?

**Comment by Artentus** [comment] 2020-09-16 08:08
Well, short of debugging yourself not really.
You'd have to load the project into Visual Studio and possibly perform a number of debug steps.

**Comment by szentigrad3** [comment] 2020-09-16 08:12
if you can read thru the steps for me or we can chat on my discord > https://discord.gg/kShyuZc

**Comment by Artentus** [comment] 2020-09-16 08:24
It's actually time to go to bed for me, we can take a look at it tomorrow.

**Comment by Artentus** [comment] 2020-09-18 03:04
Another day another attempt to fix this. If 2.2.4 works it means my PC is too fast for my own good.

**Comment by szentigrad3** [comment] 2020-09-18 03:49
> Another day another attempt to fix this. If 2.2.4 works it means my PC is too fast for my own good.
that fixed it YAY!

**Comment by Artentus** [comment] 2020-09-18 04:08
Oh my.
So the issue was that this file wasa accessed again before the previous access was complete. It was of course an oversight in my code but I never discovered it because my SSD is too fast for it to happen.

**Closed by Artentus** 2020-09-18 04:08 UTC
